// Mocks generated by Mockito 5.4.4 from annotations
// in movie_app_valu/test/features/movies/data/repository/movies_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app_valu/core/network/generic_response.dart' as _i2;
import 'package:movie_app_valu/features/movies/data/models/movie.dart' as _i5;
import 'package:movie_app_valu/features/movies/data/remote_data_source/movies_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseMoviesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseMoviesRemoteDataSource extends _i1.Mock
    implements _i3.BaseMoviesRemoteDataSource {
  @override
  _i4.Future<_i2.ApiResponse<List<_i5.Movie>>> getPopularMovies(
          {int? page = 1}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
          {#page: page},
        ),
        returnValue: _i4.Future<_i2.ApiResponse<List<_i5.Movie>>>.value(
            _FakeApiResponse_0<List<_i5.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
            {#page: page},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ApiResponse<List<_i5.Movie>>>.value(
                _FakeApiResponse_0<List<_i5.Movie>>(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
            {#page: page},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<List<_i5.Movie>>>);
}
