// Mocks generated by Mockito 5.4.4 from annotations
// in movie_app_valu/test/features/movie_details/controller/bloc/movie_details_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app_valu/core/network/failure_model.dart' as _i6;
import 'package:movie_app_valu/core/network/generic_response.dart' as _i7;
import 'package:movie_app_valu/features/movie_details/domain/entities/movie_details_entity.dart'
    as _i8;
import 'package:movie_app_valu/features/movie_details/domain/repository/base_movie_details_repository.dart'
    as _i2;
import 'package:movie_app_valu/features/movie_details/domain/usecases/get_movie_details_usecase.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseMovieDetailsRepository_0 extends _i1.SmartFake
    implements _i2.BaseMovieDetailsRepository {
  _FakeBaseMovieDetailsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetMovieDetailsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetailsUsecase extends _i1.Mock
    implements _i4.GetMovieDetailsUsecase {
  @override
  _i2.BaseMovieDetailsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeBaseMovieDetailsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeBaseMovieDetailsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.BaseMovieDetailsRepository);

  @override
  _i5.Future<
      _i3.Either<
          _i6.ApiErrorModel,
          _i7.ApiResponse<
              _i8.MovieDetails>>> getMovieDetails({required int? movieId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [],
          {#movieId: movieId},
        ),
        returnValue: _i5.Future<
                _i3.Either<_i6.ApiErrorModel,
                    _i7.ApiResponse<_i8.MovieDetails>>>.value(
            _FakeEither_1<_i6.ApiErrorModel, _i7.ApiResponse<_i8.MovieDetails>>(
          this,
          Invocation.method(
            #getMovieDetails,
            [],
            {#movieId: movieId},
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i3.Either<_i6.ApiErrorModel,
                    _i7.ApiResponse<_i8.MovieDetails>>>.value(
            _FakeEither_1<_i6.ApiErrorModel, _i7.ApiResponse<_i8.MovieDetails>>(
          this,
          Invocation.method(
            #getMovieDetails,
            [],
            {#movieId: movieId},
          ),
        )),
      ) as _i5.Future<
          _i3.Either<_i6.ApiErrorModel, _i7.ApiResponse<_i8.MovieDetails>>>);
}
