// Mocks generated by Mockito 5.4.4 from annotations
// in movie_app_valu/test/features/movie_details/data/repository/movie_details_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_app_valu/core/network/generic_response.dart' as _i2;
import 'package:movie_app_valu/features/movie_details/data/models/movie_details.dart'
    as _i5;
import 'package:movie_app_valu/features/movie_details/data/remote_data_source/movie_details_remote_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseMovieDetailsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseMovieDetailsRemoteDataSource extends _i1.Mock
    implements _i3.BaseMovieDetailsRemoteDataSource {
  @override
  _i4.Future<_i2.ApiResponse<_i5.MovieDetails>> getMovieDetails(
          {required int? movieId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [],
          {#movieId: movieId},
        ),
        returnValue: _i4.Future<_i2.ApiResponse<_i5.MovieDetails>>.value(
            _FakeApiResponse_0<_i5.MovieDetails>(
          this,
          Invocation.method(
            #getMovieDetails,
            [],
            {#movieId: movieId},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.ApiResponse<_i5.MovieDetails>>.value(
                _FakeApiResponse_0<_i5.MovieDetails>(
          this,
          Invocation.method(
            #getMovieDetails,
            [],
            {#movieId: movieId},
          ),
        )),
      ) as _i4.Future<_i2.ApiResponse<_i5.MovieDetails>>);
}
